print('########## desafio 09 ##########')
tab = int(input('Digite um valor: '))
print('Os resultados da tabuada desse número são:')
print(f'{tab} x 0 = {tab*0}')
print(f'{tab} x 1 = {tab*1}')
print(f'{tab} x 2 = {tab*2}')
print(f'{tab} x 3 = {tab*3}')
print(f'{tab} x 4 = {tab*4}')
print(f'{tab} x 5 = {tab*5}')
print(f'{tab} x 6 = {tab*6}')
print(f'{tab} x 7 = {tab*7}')
print(f'{tab} x 8 = {tab*8}')
print(f'{tab} x 9 = {tab*9}')
print(f'{tab} x 10 = {tab*10}')

